language: ruby

rvm:
- 2.2.1

before_script:
- chmod +x ./script/cibuild

script: "./script/cibuild"

branches:
  only:
  - master

deploy:
  provider: s3
  access_key_id: 
  secret_access_key:
  bucket: www.hdrzone.co.uk
  local_dir: _site
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
